# Generated by Django 2.2.24 on 2023-02-15 14:54

from django.db import migrations


def add_flats_to_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        owner = Owner.objects.get(
            owner_name=flat.owner,
            owner_pure_phone=flat.owner_pure_phone)
        flat.owners.add(owner)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230214_2014'),
    ]

    operations = [
        migrations.RunPython(add_flats_to_owner)
    ]
